## Questão 5

In [181]:
import pandas as pd
import numpy as np

In [182]:
np.random.seed(42)

In [183]:
path = "teste_smarkio_lbs.xls"
df2 = pd.read_excel(path, 'NLP')

In [184]:
df2.head()

letra  artista
0  Jay-z Uh-uh-uh You ready b? Let's go get 'em. ...  Beyoncé
1  Your challengers are a young group from Housto...  Beyoncé
2  Dum-da-de-da Do, do, do, do, do, do (Coming do...  Beyoncé
3  If I ain't got nothing I got you If I ain't go...  Beyoncé
4  Six inch heels She walked in the club like nob...  Beyoncé

In [185]:
#Shuffling da amostra
#df2 = df2.sample(frac=1)

In [186]:
df2.head()

letra  artista
0  Jay-z Uh-uh-uh You ready b? Let's go get 'em. ...  Beyoncé
1  Your challengers are a young group from Housto...  Beyoncé
2  Dum-da-de-da Do, do, do, do, do, do (Coming do...  Beyoncé
3  If I ain't got nothing I got you If I ain't go...  Beyoncé
4  Six inch heels She walked in the club like nob...  Beyoncé

In [187]:
#Codificando as artistas: Rihanna = 0 e Beyonce = 1
df2['artista'] = np.where(df2['artista']=='Rihanna',0,1)

In [188]:
df2.head()

letra  artista
0  Jay-z Uh-uh-uh You ready b? Let's go get 'em. ...        1
1  Your challengers are a young group from Housto...        1
2  Dum-da-de-da Do, do, do, do, do, do (Coming do...        1
3  If I ain't got nothing I got you If I ain't go...        1
4  Six inch heels She walked in the club like nob...        1

In [189]:
from sklearn.model_selection import train_test_split
X_treino,X_teste,y_treino,y_teste = train_test_split(df2['letra'],df2['artista'],test_size=0.3)

In [190]:
y_treino.head()

94     1
289    0
291    0
23     1
365    0
Name: artista, dtype: int32

In [191]:
#Obtenção da matriz tf-idf da amostra de treino para input no modelo
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

vetor= CountVectorizer(stop_words='english',strip_accents='unicode')
X_treino_tf = vetor.fit_transform(X_treino)

transf = TfidfTransformer()
X_treino_tfidf = transf.fit_transform(X_treino_tf)

In [192]:
print(X_treino_tf.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [193]:
from sklearn.naive_bayes import MultinomialNB
modelo = MultinomialNB().fit(X_treino_tfidf,y_treino)

In [194]:
#Preparação da amostra de validação para predição
X_teste_tf = vetor.transform(X_teste)
X_teste_tfidf = transf.transform(X_teste_tf)

In [195]:
predicao=modelo.predict(X_teste_tfidf)

In [196]:
#0 - Rihanna/ 1 - Beyonce
from sklearn import metrics

metrics.confusion_matrix(y_teste,predicao)

array([[30, 45],
       [ 5, 76]], dtype=int64)

In [197]:
from sklearn.metrics import accuracy_score, precision_score, recall_score,f1_score
acuracia = accuracy_score(y_teste,predicao)
precisao = precision_score(y_teste,predicao)
recall = recall_score(y_teste,predicao)
f1 = f1_score(y_teste,predicao)

In [198]:
print('acuracia:{},\n - precisao:{},\n - recall:{},\n - F1:{}'.
      format(acuracia,precisao,recall,f1))

acuracia:0.6794871794871795,
 - precisao:0.628099173553719,
 - recall:0.9382716049382716,
 - F1:0.7524752475247526
